src/main.py
Based on a [comment](https://github.com/codersrank-org/repo_info_extractor/issues/2#issuecomment-506922927), thanks for [giansalex](https://github.com/giansalex)!
fix 2
fix 4
=> main module added

run.bat
=> Complete run.bat

README.md
=> Updated Windows instructions.

src/analyze_repo.py
Fix for the bug of the repo_extractor on windows (#11). The problem was caused by the multiprocessing library-s different behaviour on windows.
=> windows bug fix

README.md
=> Fix result filename in README

src/language/Go.py, test/fixtures/Go.go, test/test_Go.py
=> Add Go library parsing

src/language/detect_language.py, test/test_detect_language.py
=> Add Dart language support

src/language/detect_language.py
=> add PLSQL files for detection

test/test_detect_language.py
Add tests for PSQL language detection
=> Add tests for PSQL language detection

src/init.py
=> Add email count limit to headless mode.

requirements.txt, src/identity_matching/matcher.py
for shortlog UnicodeDecodeError.
=> use utf-8 encoding

src/identity_matching/matcher.py
use latin-1 instead of utf-8 because looks like it is working better
=> Change on encodings for shortlog

src/init.py, src/language/Python.py, src/timeout/timeout.py
Adds timeout to init_headless. The amount of seconds must be passed as argument to init_headless.
=> Timeout for init_headless

src/analyze_repo.py, src/entity/commit.py, src/identity_matching/matcher.py, src/language/detect_language.py, test/generated/result.json, test/test_repo.py
- sanitize filenames because if they are not ascii, git pulls double quotes around them.
- added a functional test for creating repo
- small formattings
=> Sanitize filenames

src/analyze_repo.py
Apparently some people like files with a single letter names.
=> add control for path length

src/language/TypeScript.py
for detecting libraries from typescript files.
Actually I just copied JavaScript file and renamed it TypeScript. It should work fine for most of the cases.
=> Add typescript support

src/language/C.py, test/fixtures/C.c, test/test_C.py
Referencing #44 , this PR will allow the extraction of libraries used in C source files. Should also work for #45 .
=> Extracts libraries used in C source files

run-docker.ps1
Added a script for powershell (.ps1 file)
=> Add Powershell script to run on Docker

src/language/detect_language.py
=> Adds Raku extensions

src/language/Kotlin.py, test/fixtures/Kotlin.kt, test/fixtures/credits.txt, test/test_Kotlin.py
=> added Kotlin library extraction

src/language/C++.py, test/fixtures/Cpp.cpp, test/test_C++.py
Added code and test for extracting libraries from c++. Closes #45
=> Extract libraries from cpp

src/language/detect_language.py, test/test_detect_language.py
Puppet is a software configuration management tool.  It has it's own language
to describe the expected systems configuration:
https://puppet.com/docs/puppet/latest/puppet_language.html
=> Add Puppet language

src/language/detect_language.py, test/test_detect_language.py
QML (Qt Modeling Language) is a user interface markup language.
=> Add QML language

src/language/detect_language.py, test/test_detect_language.py
EPP is to Puppet what ERB is to Ruby.
=> Add EPP marckup language

.gitignore, extractor/extractor.go, languagedetection/analyzer.go
And a little bit refactoring. Moved language detection to its own package from extractor.
=> Add Perl Support

emailsimilarity/similarity.go
add users.noreply.github.com to filtered domains in email detection
=> Ingore github domains for email similarity

extractor/extractor.go
```
Error during getting commits. Error: exec: "C:\\Program Files\\Git\\cmd\\git.exe\r\nC:\\Program Files\\Git\\mingw64\\bin\\git.exe": file does not exist
```
fixed, please review.
=> fixed multifile git path in windows.

languagedetection/analyzer.go
Ballerina is an open-source language for cloud. Check out the [Ballerina website](https://ballerina.io).
=> Add Ballerina Language to Language Detection

languagedetection/analyzer.go, languagedetection/analyzer_test.go
Tested locally, successfully detected generic "SQL" and "PL/pgSQL" variant via enry.
=> Detect SQL dialects from *.sql files

languagedetection/analyzer.go, languagedetection/analyzer_test.go
`Jenkinsfile` is a common part of many software projects which describes build/test/deploy steps.
https://github.com/search?p=1&q=filename%3AJenkinsfile&type=Code
Jenkins Pipeline is a suite of plugins which supports implementing and integrating continuous delivery pipelines into Jenkins.
The definition of a Jenkins Pipeline is written into a text file (called a Jenkinsfile) which in turn can be committed to a project’s source control repository. This is the foundation of "Pipeline-as-code"; treating the CD pipeline a part of the application to be versioned and reviewed like any other code.
Pipeline provides an extensible set of tools for modeling simple-to-complex delivery pipelines "as code" via the Pipeline domain-specific language (DSL) syntax. …
=> Detect pipeline-as-a-code files for Jenkins

languagedetection/analyzer.go
Solidity is a programming language designed for developing smart contracts that run on Ethereum
=> Added Solidity language detection

languagedetection/analyzer.go
Adds [PureScript language](https://purescript.org/)
=> Add PureScript language
